// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: server/error_reason.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_SUCCESS        ErrorReason = 0
	ErrorReason_USER_NOT_FOUND ErrorReason = 1
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "SUCCESS",
		1: "USER_NOT_FOUND",
	}
	ErrorReason_value = map[string]int32{
		"SUCCESS":        0,
		"USER_NOT_FOUND": 1,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_server_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_server_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_server_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_server_error_reason_proto protoreflect.FileDescriptor

const file_server_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x19server/error_reason.proto\x12\n" +
	"api.server*.\n" +
	"\vErrorReason\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\x01B1\n" +
	"\n" +
	"api.serverP\x01Z!server-template/api/server;serverb\x06proto3"

var (
	file_server_error_reason_proto_rawDescOnce sync.Once
	file_server_error_reason_proto_rawDescData []byte
)

func file_server_error_reason_proto_rawDescGZIP() []byte {
	file_server_error_reason_proto_rawDescOnce.Do(func() {
		file_server_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_error_reason_proto_rawDesc), len(file_server_error_reason_proto_rawDesc)))
	})
	return file_server_error_reason_proto_rawDescData
}

var file_server_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.server.ErrorReason
}
var file_server_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_error_reason_proto_init() }
func file_server_error_reason_proto_init() {
	if File_server_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_error_reason_proto_rawDesc), len(file_server_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_error_reason_proto_goTypes,
		DependencyIndexes: file_server_error_reason_proto_depIdxs,
		EnumInfos:         file_server_error_reason_proto_enumTypes,
	}.Build()
	File_server_error_reason_proto = out.File
	file_server_error_reason_proto_goTypes = nil
	file_server_error_reason_proto_depIdxs = nil
}
