// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, name string) (int64, error)
	CreateUserDetail(ctx context.Context, arg CreateUserDetailParams) (int64, error)
	QueryUsers(ctx context.Context) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
