// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_detail.sql

package queries

import (
	"context"
)

const createUserDetail = `-- name: CreateUserDetail :execlastid
INSERT INTO user_detail (user_id,email) VALUES (?,?)
`

type CreateUserDetailParams struct {
	UserID int64  `json:"user_id"`
	Email  string `json:"email"`
}

func (q *Queries) CreateUserDetail(ctx context.Context, arg CreateUserDetailParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createUserDetail, arg.UserID, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
